context:
  name: changelist
  version: 0.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/changelist-${{ version }}.tar.gz
  sha256: 767f53764bce6cec406afeaf90a095e7b2599525e80032ac7a94941fbe65167a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - changelist = changelist.__main__:main

requirements:
  host:
    - python >=3.9
    - setuptools >=68.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - requests
    - requests-cache
    - tqdm
    - pygithub

tests:
  - python:
      imports:
        - changelist
  - requirements:
      run:
        - pip
    script:
      - pip check
      - changelist --help

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  repository: https://github.com/scientific-python/changelist
  homepage: https://github.com/scientific-python/changelist
  summary: A tool that automates release note generation.
  
extra:
  recipe-maintainers:
    - MridulS
